name: Deploy to Hostinger
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'
    - name: Check Node.js and npm versions
      run: |
        node -v
        npm -v
    - name: Clean npm cache
      run: npm cache clean --force
    - run: npm install
    - run: npm ci
    - name: Build project
      run: |
        npm run build
        echo "Build directory contents:"
        ls -la build
    - run: ls -R build
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 62.72.37.112
        username: u875133030.Govetia
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
        server-dir: /